### ISSUE TITLE
package-list may not be produced if the plugin is configured in the parent POM of a modular Maven build

### ISSUE THREAD

**Issue by carlosame** [networknt/javadoc-packagelist-maven-plugin#2]
In a Maven modular project, the package-list file is produced if I configure the plugin in the POM of a specific module, but not if I set it up in the parent's POM:

```xml
<plugin>
	<groupId>com.networknt</groupId>
	<artifactId>javadoc-packagelist-maven-plugin</artifactId>
	<version>1.0.0</version>
	<executions>
		<execution>
			<phase>package</phase>
			<goals>
				<goal>gen-package-list</goal>
			</goals>
		</execution>
	</executions>
</plugin>

```
I found the problem while trying to add this plugin to the build of css4j (its parent POM is [`css4j-dist`](/css4j/css4j-dist)), so you could use that project to reproduce the issue but the build is not particularly easy to set up (requires `svn` to retrieve the module sources).

**Comment by stevehu** [comment]
@carlosame We are using it in the parent pom.xml only and most of our projects have multiple modules. Could you please take a look at the light-rest-4j project to see what is the difference compare with yours? Thanks. 

BTW, only the master branch which is on Java 11 needs this plugin.

**Comment by carlosame** [comment]
Thanks @stevehu for the fast answer. It is not immediately apparent which entry may be causing the problem, but an obvious difference is that my javadoc-plugin configuration requires the following to build:

```xml
<source>8</source>
<doclint>none</doclint>
```

I guess that it could have something to do with that, however there is another project (JCLF, non-modular) where I do not obtain the `package-list` when building with a recent JDK (tested with 13 and 14):

https://sourceforge.net/p/jclf/main/ci/master/tree/pom.xml

My two projects have something in common: they do not have the standard Maven directory layout.

**Comment by carlosame** [comment]
It turns out that I did not configure the plugin at the place where I should. Closing, although I still have the issue at the other project (but it is not this same one).
