### ISSUE TITLE
Exclude packages from package-list

### ISSUE THREAD

**Issue by carlosame** [networknt/javadoc-packagelist-maven-plugin#3]
I'm using the `javadoc-packagelist-maven-plugin` to produce a `package-list` for a modular project where one of the packages is not exported.  As I generate the Javadocs with a `<source>7</source>` configuration, I have a `<excludePackageNames>` in the `maven-javadoc-plugin` section of the POM.

The javadocs do not include the package that is not exported, but the `package-list` does. How could I configure the plugin to not include that package?

**Comment by stevehu** [comment]
@carlosame This plugin is originally designed for light-4j projects when we move to Java 11. It never considered any extra use cases. The source code is available and I am open to any enhancements.

**Comment by carlosame** [comment]
> never considered any extra use cases

Thank you, I was unaware of that. I'll see if I can clone it and reach some result.
