### ISSUE TITLE
Projects without a parent POM are not being processed

### ISSUE THREAD

**Issue by carlosame** [networknt/javadoc-packagelist-maven-plugin#5]
The plugin only produces the `package-list` for modular Maven projects; I'm preparing a pull request that fixes this issue.

**Comment by carlosame** [comment]
Thanks @stevehu for merging.

**Comment by stevehu** [comment]
I am sure that you have subsequent changes in the draft PR. Just make sure that you sync your local copy from the original. Thanks.
